name: coverage

on:
  push:
    branches:
      - 'main'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          pip install mock pytest pytest-cov
          pip install -r requirements.txt
          python -m pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests